name: Clear all cache

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          [ -z "$(gh cache list)" ] || gh cache delete --all