name: Build WSL Distro custom

on:
  workflow_dispatch:

# Variables in the env map cannot be defined in terms of other variables in the map
env:
  DOCKERHUB_USERNAME: maumauricelim

jobs:
  build:
    timeout-minutes: 5
    strategy:
      matrix:
        BASE_IMAGE: [ ubuntu, alpine ]
    runs-on: ubuntu-latest
    env:
        IMAGE_NAME: ${{ matrix.BASE_IMAGE }}-custom
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and load
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.${{ matrix.BASE_IMAGE }}
      - name: Upload docker image to registry
        run: docker image push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
      - name: Export docker container to a tar.gz file using gzip
        run: |
          docker run -dit --hostname ${{ env.IMAGE_NAME }} --name ${{ env.IMAGE_NAME }} ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker export ${{ env.IMAGE_NAME }} | gzip > /tmp/${{ env.IMAGE_NAME }}.tar.gz
      - name: Export WSL install script
        run: sed "s/SET_DISTRO_NAME/${{ env.IMAGE_NAME }}/g" src/install.cmd > /tmp/install.cmd
      - name: Upload WSL image
        uses: actions/upload-artifact@v4
        with:
          name: wsl-${{ env.IMAGE_NAME }}
          path: |
            /tmp/${{ env.IMAGE_NAME }}.tar.gz
            /tmp/install.cmd